### ISSUE TITLE
Refactor code for use without UI

### ISSUE THREAD

**Issue by tischi** [BIOP/bigdataviewer-bioformats#1]
It would be great to also be able to use the code without the UI. For example, I could not figure out how to load two images into the same BDV Windows, programmatically. If you don't mind, I could try to refactor the code a bit to improve, imho, readability and usability without the UI. I am not implying I can write cleaner code than you, but I think that code always improves if a second person takes a look at it. Let me know what you think; I could work on it during the coming days.

**Comment by tischi** [comment]
I take it back. In fact one can use it quite nicely from the code:
https://github.com/tischi/bigdataviewer-bioformats/blob/master/src/test/java/explore/ExploreOpeningImages.java#L12

**Comment by NicoKiaru** [comment]
Hi @tischi , 
Cool! Actually I wasn't sure it would work because of the `CommandService` required. But it's injected thanks to Scijava magic. Great!
But you are right that the logic is not separated between `Command`  and `Sources` . If you need the sources without display, then it's not good.
Of course I have no problem with you modifying the code. Just let me know before (as you did) what are the limitations so that we try to avoid duplicating the work.

**Comment by NicoKiaru** [comment]
Just a small trick badly documented; hidden but useful: you can easily specify which series/channels combination you want to open with a the `sourceIndexStringNewFull` String parameter (bad name btw)
```
command.sourceIndexStringNewFull = "*.*" 
// convention is serie.channel so:
// all series all channels : "*.*" or "*", by convention, all channels are open
// all series first channel : "*.0"
// first series all channels : "0.*"
// first series third channel : "0.2"
// all series last channel : "*.-1"
// serie 1 to 3, second channel : "0:2.2"
// tricky : serie 3 to last, last two channels for each serie : "2:-1.-2:-1"
```

Not specifying the channels leads to all channels being open.

**Comment by NicoKiaru** [comment]
By the way, another option to add / remove source etc, is to use the repo:

https://github.com/BIOP/bigdataviewer_scijava

That's actually why this repo was made with commands and bigdataviewer handles. But I've splitted them because they are doing different stuff. But if you declare this extra repo as a dependency for runtime, then you have tools to manipulate a bit the sources between different windows.

**Comment by NicoKiaru** [comment]
> 
> 
> I take it back. In fact one can use it quite nicely from the code:
> https://github.com/tischi/bigdataviewer-bioformats/blob/master/src/test/java/explore/ExploreOpeningImages.java#L12

You should try to set `command.unit="Microns"` and look at how it behaves.
