### ISSUE TITLE
Open as Source

### ISSUE THREAD

**Issue by tischi** [BIOP/bigdataviewer-bioformats#11]
I would like to add code such that one can open a file as a `Source`, but at the same time I would like to also provide information needed to render the file with a proper `LUT`.

One option would be to return an object like this:
- https://github.com/tischi/bdv-utils/blob/render/src/main/java/de/embl/cba/bdv/utils/sources/SourceAndVolatileARGBConverter.java#L21

As constructed, e.g., here:
- https://github.com/tischi/bdv-utils/blob/render/src/main/java/de/embl/cba/bdv/utils/io/SPIMDataReaders.java#L38

However, maybe it is more versatile to have a class `SourceReader` and then have methods like 
```
SourceReader( file )
getSource()
getColor()
getLutMin()
getLutMax()
```
What do you think?

**Comment by NicoKiaru** [comment]
That's something which has a broader applicability than this repo. I'd rather keep it apart.

Also we do not know yet how things are gonna turn with the long-needed color map display.  It's better to keep the implementation minimal regarding display settings in this repo, don't you think ?

Maybe in the xml dataset export, it would be nice to have a `dataset.settings.xml` which give at least reasonable display settings.

**Comment by tischi** [comment]
But don't you think this repo should also provide users with a `Source` object, created from a bio-formats compatible filename. Rather than just displaying it in Bdv?

Essentially it is only putting this code in a separate function:
- https://github.com/BIOP/bigdataviewer-bioformats/blob/master/src/main/java/ch/epfl/biop/bdv/bioformats/command/BioFormatsOpenSingleSourceInBdvCommand.java#L109

And then consume the `Source` here:
- https://github.com/BIOP/bigdataviewer-bioformats/blob/master/src/main/java/ch/epfl/biop/bdv/bioformats/command/BioFormatsOpenSingleSourceInBdvCommand.java#L158

Because right now, the `Command` is doing in fact three things:
- Providing the UI
- Loading the Source
- Displaying the Source in Bdv

I would split this in 3 classes.
I can do a PR and you could have a look.

**Comment by NicoKiaru** [comment]
I also worked on it. And I think you are perfectly right, this repo does too many things. I plan to remove completely the UI, and it will just provide sources. Even the volatile wrapping is not strictly necessary. I'll remove it. I'll push my changes.

**Comment by NicoKiaru** [comment]
Pushed. I modified really heavily the repo, but now it's much more focused on its objective. All the code that was present in duplicate/triplicate is removed. I have very little time to work further on it this week, but let me know what you think.

**Comment by tischi** [comment]
> Even the volatile wrapping is not strictly necessary.

I guess that's the point where we are both still confused?
I was in fact now doubting what to return, because if it is a `Source`, I think we already have to decide whether it is `Volatile` or not, right?! Which is not ideal, because it depends whether one wants to compute on it or view it with the Bdv.

Maybe another idea would be to provide a `MultiResolutionSetupImgLoader` rather than a `Source`, because then one would have still access to both the `Volatile` and `NonVolatile` versions of the data.

What do you think?

**Comment by NicoKiaru** [comment]
> I guess that's the point where we are both still confused?

Yep. That's the thing we discussed. Here's my understanding of the mechanism and how it works in the repo:

So in the repo, the BioFormat images can be opened in two ways, one that requires a conversion (two steps) and one which does not require a conversion (one step):
* Two steps way : 
** Step 1 : convert some files into a xml bdv dataset, using the Command https://github.com/BIOP/bigdataviewer-bioformats/blob/master/src/main/java/ch/epfl/biop/bdv/bioformats/export/xmlbdvdataset/BioFormatsConvertFilesToXmlDataset.java
** Step 2: When doing this, the dataset (an xml file) can be opened using the standard `Open Xml/Hdf5` command from bigdataviewer, provided the bioformats image loader can be found in the classpath (this class here : https://github.com/BIOP/bigdataviewer-bioformats/blob/master/src/main/java/ch/epfl/biop/bdv/bioformats/imageloader/XmlIoBioFormatsImgLoader.java). This loader is found via the `format` attribute in the ` ImgLoaderIo` annotation, which happen to be also present in the xml dataset file.
* One step way: Using the functions in the BioFormatsBdvOpener to directly access sources. But then, because the Source are not autoamtically wrapped to Volatile via BdvFunctions (cf your gitter point), it's currently up to us to decide whether we want to get a Volatile source or a concrete Source. Nonetheless this way of opening the data is more direct. So it's convenient to have them accessible. Also, this way of accessing the Source is used by the image loader itself:
https://github.com/BIOP/bigdataviewer-bioformats/blob/4acffcc64d48e67ec31087187d9cb7807db7a72e/src/main/java/ch/epfl/biop/bdv/bioformats/imageloader/BFViewerImgLoader.java#L57-L67
 So it's necessary currently anyway.

In the two step way, BigDataViewer is clever enough to get the volatile sources when displaying and giving the concrete sources when required. This is because the wrapping is present in the image loader. In the one step way, it's up to us to decide.

**Comment by NicoKiaru** [comment]
> Maybe another idea would be to provide a `MultiResolutionSetupImgLoader` rather than a `Source`, because then one would have still access to both the `Volatile` and `NonVolatile` versions of the data.

So in the two step way, that's what we have. The setup loader is implementing a `MultiResolutionSetupImgLoader`:

https://github.com/BIOP/bigdataviewer-bioformats/blob/4acffcc64d48e67ec31087187d9cb7807db7a72e/src/main/java/ch/epfl/biop/bdv/bioformats/imageloader/BFViewerImgLoader.java#L30

But I'm not sure it's the `MultiResolutionImgLoader` which is important for having both volatile and non volatile. It's rather the fact that it's extending an  `AbstractViewerSetupImgLoader< T, V extends Volatile< T > >`

**Comment by tischi** [comment]
II also thought about it again, and maybe, in the end, I finally understand the `SpimData` object. This contains all the information and accesses. Even though it is a monster class that I never thought I would work with, but maybe that's simply what we should return. In the end this is also what is created by the `XmlLoader`. What do you think?

**Comment by NicoKiaru** [comment]
Yes, we could use the `SpimData` object. It is created here currently,

https://github.com/BIOP/bigdataviewer-bioformats/blob/4acffcc64d48e67ec31087187d9cb7807db7a72e/src/main/java/ch/epfl/biop/bdv/bioformats/export/xmlbdvdataset/BioFormatsConvertFilesToXmlDataset.java#L208-L209

but it is not accessible. We can make it as an output of this command. I don't know how the SpimData object can be constructed without a linked xml file however.

**Comment by tischi** [comment]
> I don't know how the SpimData object can be constructed without a linked xml file however.

Yes, me neither :-)

**Comment by NicoKiaru** [comment]
> I don't know how the SpimData object can be constructed without a linked xml file however.

Yes it can. I added an example to open a file either by getting the Sources:

https://github.com/BIOP/bigdataviewer-bioformats/blob/master/src/test/java/explore/OpenAndDisplayImageWithSource.java

or by converting before with to a SpimDataObject:

https://github.com/BIOP/bigdataviewer-bioformats/blob/master/src/test/java/explore/OpenAndDisplayImageWithSpimData.java

There are moreover examples on how to get the proper channel color in this test classes. For the moment I think it's good to have an idea on how to set LUT and min max in the test class, but let's not make it part of the repo. We have to wait what's going on with `BdvFunctions` beforehand.

**Comment by tischi** [comment]
Yes, let's see. Given our latest discussion on gutter maybe several `SourceAndConverter` would be a more concise way of representing the data internally, rather than the very convoluted `SpimData`

**Comment by NicoKiaru** [comment]
Yep, for sure, but the spimdata is great for xml/h5 dataset compatability -> bigstitcher registration is possible easily
