### ISSUE TITLE
Methods questions

### ISSUE THREAD

**Issue by tischi** [BIOP/bigdataviewer-bioformats#18]
@NicoKiaru @ssgpers

Could you please explain us what this is? Do we need to set it? What are the consequences?
`BioFormatsBdvOpener.positionReferenceFrameLength`
Thanks!

**Comment by NicoKiaru** [comment]
@tischi 


https://forum.image.sc/t/improve-bio-formats-image-position-metadata/30770/3

And I didn't get any answer. From what I've observed : this is the unit put by default in Bio Formats when it doesn't know a physical unit. This is use for instance for thickness of a 2d only image. Now in the bridge bdv bioformats, you can choose a unit.

*  If you choose `mm` and put a referenceframelength of 1, you'll get a thickness of 1 mm for your 2d image.
*  If you choose `cm` and put a referenceframelength of 1, you'll get a thickness of 1 cm for your 2d image.

Hope that helps, otherwise let's ask ome team on the forum

**Comment by tischi** [comment]
Makes sense, but it is crashing for us if this is not set manually (see other issue).
Maybe your code could crash with some message telling that this should be set?

**Comment by NicoKiaru** [comment]
Yep, makes sense

**Comment by NicoKiaru** [comment]
Finally, I've put some default values (1 micron for both). Much more simple than handling all errors if they occur

**Comment by NicoKiaru** [comment]
Related commit : https://github.com/BIOP/bigdataviewer-bioformats/commit/360ced38d46b96ad2b962a0d6adf1fea56de23f5
