### ISSUE TITLE
LUT support

### ISSUE THREAD

**Issue by tischi** [BIOP/bigdataviewer-bioformats#21]
@NicoKiaru 
Which LUTs do you support in your reader?
For example, if your code would open an `imageplus.tif` which has been saved with a `glasbey inverted` LUT, would that be translated into a matching `Converter`? I guess not, or? I also think this may be too much work to support and it is non-standard since it is very IJ specific...

**Comment by NicoKiaru** [comment]
I'm only supporting ARGB colors with ARGBType.

Partly because it's the most standard for Bdv, also because I don't know how more complex LUTs are supported with bioformats.

The issue comes from both sides!

RIght now I think I'm testing  a few fields from the bioformats API to check if a color is defined (emission wavelength and getchannelcolor). If I don't find anything then the color is white.

**Comment by tischi** [comment]
ok!
