### ISSUE TITLE
Voxel Dimensions

### ISSUE THREAD

**Issue by tischi** [BIOP/bigdataviewer-bioformats#4]
It looks like you are currently **_not_** reading the voxel dimensions?!

- https://github.com/BIOP/bigdataviewer-bioformats/blob/master/src/main/java/ch/epfl/biop/bdv/bioformats/bioformatssource/BioFormatsBdvSource.java#L148

**Comment by NicoKiaru** [comment]
That's right, forgot about this.

One trick though, is that again the metadata can be specified in an xml dataset / image loader or directly within the `BioFormatsOpenPlugInSciJava`. When the source is required from `BioFormatsOpenPlugInSciJava`, you want to get the metadata right, hence set the `ignoreMetadata` flag to `false`. However, when using a setup loader (https://github.com/BIOP/bigdataviewer-bioformats/blob/master/src/main/java/ch/epfl/biop/bdv/bioformats/imageloader/BFViewerImgLoader.java), the metadata should be ignored, because it's already specified in the xml dataset file. (see xml dataset export : https://github.com/BIOP/bigdataviewer-bioformats/blob/4e950c729538b3d6a4a455b3d10033aa4b74b83f/src/main/java/ch/epfl/biop/bdv/bioformats/export/xmlbdvdataset/BioFormatsConvertFilesToXmlDataset.java#L124-L125 and https://github.com/BIOP/bigdataviewer-bioformats/blob/4e950c729538b3d6a4a455b3d10033aa4b74b83f/src/main/java/ch/epfl/biop/bdv/bioformats/export/xmlbdvdataset/BioFormatsConvertFilesToXmlDataset.java#L187)

So in the setup loader, this flag is set to `true`: https://github.com/BIOP/bigdataviewer-bioformats/blob/4e950c729538b3d6a4a455b3d10033aa4b74b83f/src/main/java/ch/epfl/biop/bdv/bioformats/imageloader/BFViewerImgLoader.java#L72

So when modifying the code, one need to take care that it works in both cases : the plugin or through the xml dataset and imageloader.

We could drop the plugin and just keep the image loader, but I think it's nice to be able to avoid the xml dataset conversion.

**Comment by tischi** [comment]
I have another question. 

You `try` to read the voxelSize here:
- https://github.com/BIOP/bigdataviewer-bioformats/blob/master/src/main/java/ch/epfl/biop/bdv/bioformats/BioFormatsHelper.java#L121

But in the `catch` you fall back to using the image dimensions as pixel size. Is that on purpose?
- `dXmm = omeMeta.getPixelsSizeX(iSerie).getNumberValue().doubleValue();`

**Comment by NicoKiaru** [comment]
AAaaahhhh I did do that. That's just plain stupid. 

I may have thought that it was returning a meaningful value when the units were not specified, but actually it's the number of pixel. Beurk.

**Comment by tischi** [comment]
the names of the methods are also really confusing!

**Comment by NicoKiaru** [comment]
should be done in commit https://github.com/BIOP/bigdataviewer-bioformats/commit/647d429ad0241e677efa0f4d65f98b2f7d336e4f
